package org.wordtrail.ime;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Typeface;
import android.os.Bundle;
import android.provider.Settings;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;

public final class MainActivity extends Activity {
    private WordtrailStyle palette;
    private LinearLayout content;
    private EditText test;
    private TextView speechAvailability;
    @Override public void onCreate(Bundle state){super.onCreate(state);showHome();}
    @Override public void onResume(){super.onResume();if(palette!=null && !palette.id.equals(WordtrailStyle.load(this).id))showHome();if(speechAvailability!=null)speechAvailability.setText(voiceDescription());}
    private void showHome(){
        String draft=test==null?"":test.getText().toString();palette=WordtrailStyle.load(this);
        getWindow().setStatusBarColor(palette.background);getWindow().setNavigationBarColor(palette.background);
        getWindow().getDecorView().setSystemUiVisibility(palette.id.equals("night")?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(palette.background);scroll.setClipToPadding(false);
        content=column();content.setPadding(dp(20),dp(18),dp(20),dp(24));content.setFocusableInTouchMode(true);scroll.addView(content);setContentView(scroll);content.requestFocus();
        if(android.os.Build.VERSION.SDK_INT>=30){scroll.setOnApplyWindowInsetsListener((view,insets)->{android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars());android.graphics.Insets keyboard=insets.getInsets(WindowInsets.Type.ime());view.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,keyboard.bottom));if(keyboard.bottom>0)view.post(()->{View focused=view.findFocus();if(focused instanceof EditText){android.graphics.Rect rect=new android.graphics.Rect();focused.getDrawingRect(rect);focused.requestRectangleOnScreen(rect,false);}});return insets;});scroll.requestApplyInsets();}else scroll.setFitsSystemWindows(true);
        LinearLayout header=row();header.setGravity(Gravity.CENTER_VERTICAL);
        ImageView mark=new ImageView(this);mark.setImageResource(R.drawable.wordtrail_mark);mark.setScaleType(ImageView.ScaleType.FIT_CENTER);mark.setContentDescription("词伴小书灵图标");mark.setBackground(palette.shape(this,0xFFFFF9EA,0,16));mark.setClipToOutline(true);header.addView(mark,new LinearLayout.LayoutParams(dp(48),dp(48)));
        LinearLayout title=column();title.setPadding(dp(12),0,0,0);title.addView(label("词伴输入法",23,palette.ink,true));TextView english=label("WORDTRAIL",10,palette.muted,false);english.setLetterSpacing(.15f);title.addView(english);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));
        TextView local=label("本地词库",11,palette.accent,true);local.setPadding(dp(10),dp(6),dp(10),dp(6));local.setBackground(palette.shape(this,palette.soft,0,20));header.addView(local);content.addView(header);
        TextView headline=label("好好打字，\n顺便认识一个新单词。",25,palette.ink,true);headline.setLineSpacing(dp(3),1);add(headline,18);add(label("中文是主角，译词轻轻陪伴。",13,palette.muted,false),5);
        LinearLayout languageCard=card(12);languageCard.addView(label("学习语言",13,palette.muted,true));RadioGroup languages=choices(new String[]{"英语","日语","西班牙语"},new String[]{"en","ja","es"},"language","en",false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(40));lp.topMargin=dp(7);languageCard.addView(languages,lp);add(languageCard,16);
        LinearLayout trial=card(14);LinearLayout trialHeader=row();trialHeader.setGravity(Gravity.CENTER_VERTICAL);trialHeader.addView(label("试打一下",15,palette.ink,true),new LinearLayout.LayoutParams(0,-2,1));trialHeader.addView(label("nihao → 你好 / hello",11,palette.muted,false));trial.addView(trialHeader);
        test=new EditText(this);test.setText(draft);test.setTextSize(19);test.setTextColor(palette.ink);test.setHintTextColor(palette.muted);test.setHint("在这里输入拼音…");test.setMinLines(2);test.setGravity(Gravity.TOP);test.setPadding(dp(12),dp(12),dp(12),dp(10));test.setBackground(palette.shape(this,palette.background,0,12));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,dp(76));tp.topMargin=dp(10);trial.addView(test,tp);add(trial,12);
        LinearLayout setup=card(14);setup.addView(label("让词伴陪你打字",16,palette.ink,true));TextView hint=label("启用键盘，再切换到词伴，就准备好了。",12,palette.muted,false);hint.setPadding(0,dp(5),0,dp(12));setup.addView(hint);setup.addView(button("① 启用词伴键盘",true,v->startActivity(new Intent(Settings.ACTION_INPUT_METHOD_SETTINGS))),new LinearLayout.LayoutParams(-1,dp(46)));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.topMargin=dp(8);setup.addView(button("② 切换到词伴",false,v->((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showInputMethodPicker()),cp);add(setup,12);
        LinearLayout themes=card(14);themes.addView(label("换一种心情",16,palette.ink,true));TextView themeHint=label("三套主题，也能在键盘上点 ◐ 切换。",12,palette.muted,false);themeHint.setPadding(0,dp(5),0,dp(10));themes.addView(themeHint);themes.addView(choices(new String[]{"青绿","粉紫","深色"},new String[]{"jade","lavender","night"},"theme","jade",true),new LinearLayout.LayoutParams(-1,dp(44)));add(themes,12);
        LinearLayout goals=card(14);goals.addView(label("英语学习目标",16,palette.ink,true));
        TextView goalsHint=label("可多选，优先显示对应的英文译词。中文候选顺序不变，其他译词仍保留。",12,palette.muted,false);goalsHint.setPadding(0,dp(6),0,dp(8));goals.addView(goalsHint);
        android.content.SharedPreferences prefs=getSharedPreferences("settings",MODE_PRIVATE);
        int selected=prefs.getInt("vocabulary_targets",0);
        CheckBox[] targets=new CheckBox[VocabularySettings.IDS.length];
        TextView selectionHint=label(selected==0?"全部词汇 · 原译词顺序":"已选择学习目标 · 命中译词优先",11,palette.accent,false);
        for(int r=0;r<2;r++){LinearLayout targetRow=row();for(int c=0;c<3;c++){int index=r*3+c;CheckBox option=new CheckBox(this);targets[index]=option;option.setText(VocabularySettings.LABELS[index]);option.setContentDescription("优先"+VocabularySettings.LABELS[index]+"译词");option.setTextSize(13);option.setTextColor(palette.ink);option.setButtonTintList(android.content.res.ColorStateList.valueOf(palette.accent));option.setChecked((selected&(1<<index))!=0);option.setOnCheckedChangeListener((button,checked)->{int mask=0;for(int n=0;n<targets.length;n++)if(targets[n]!=null && targets[n].isChecked())mask|=1<<n;prefs.edit().putInt("vocabulary_targets",mask).apply();selectionHint.setText(mask==0?"全部词汇 · 原译词顺序":"已选择学习目标 · 命中译词优先");});targetRow.addView(option,new LinearLayout.LayoutParams(0,dp(44),1));}goals.addView(targetRow);}
        goals.addView(selectionHint);Button all=button("全部词汇 / 清除目标",false,v->{for(CheckBox target:targets)target.setChecked(false);});goals.addView(all,new LinearLayout.LayoutParams(-1,dp(42)));
        Switch showTags=new Switch(this);showTags.setText("候选显示考试标签");showTags.setContentDescription("候选显示考试标签");showTags.setTextColor(palette.ink);showTags.setTextSize(13);showTags.setChecked(prefs.getBoolean("show_vocabulary_tags",true));showTags.setOnCheckedChangeListener((button,checked)->prefs.edit().putBoolean("show_vocabulary_tags",checked).apply());goals.addView(showTags,new LinearLayout.LayoutParams(-1,dp(42)));
        TextView sourceHint=label("同一个词可有多个标签。社区词表标记仅表示收录类别，不代表难度或官方完整考试范围。展开候选可查看全部标签与来源。",11,palette.muted,false);sourceHint.setLineSpacing(dp(2),1);goals.addView(sourceHint);add(goals,12);
        LinearLayout voice=card(14);voice.addView(label("语音输入",16,palette.ink,true));TextView voiceHint=label("点键盘顶部麦克风说话。默认本机离线识别，不需系统服务；中文 / 英文跟随中/英键。",12,palette.muted,false);voiceHint.setPadding(0,dp(6),0,dp(8));voice.addView(voiceHint);
        voice.addView(choices(new String[]{"本机离线","系统语音"},new String[]{"local","system"},"speech_engine","local",true),new LinearLayout.LayoutParams(-1,dp(40)));
        Switch systemVoice=new Switch(this);systemVoice.setText("允许系统语音服务（可能联网）");systemVoice.setTextSize(12);systemVoice.setTextColor(palette.ink);systemVoice.setChecked(getSharedPreferences("settings",MODE_PRIVATE).getBoolean("speech_allow_system",false));systemVoice.setOnCheckedChangeListener((button,checked)->getSharedPreferences("settings",MODE_PRIVATE).edit().putBoolean("speech_allow_system",checked).apply());voice.addView(systemVoice);
        systemVoice.setVisibility(getSharedPreferences("settings",MODE_PRIVATE).getString("speech_engine","local").equals("system")?View.VISIBLE:View.GONE);
        speechAvailability=label(voiceDescription(),11,palette.muted,false);speechAvailability.setPadding(0,dp(8),0,0);voice.addView(speechAvailability);
        Button speechSettings=button("语音设置与诊断",false,v->startActivity(new Intent(this,SpeechSettingsActivity.class)));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(44));sp.topMargin=dp(8);voice.addView(speechSettings,sp);add(voice,12);
        TextView privacy=label("点选输入中文 · 长按输入译词\n拼音、词库、音标与熟悉度均在本地运行。\n默认离线语音在本机处理，不上传、不保存录音。选择系统服务时，该服务可能联网。",12,palette.muted,false);privacy.setLineSpacing(dp(5),1);add(privacy,16);Button notices=button("开源许可与数据来源",false,v->showNotices());notices.setTextSize(12);add(notices,12);TextView version=label("独立移动实验版 0.1.9 · 基于青简开源内核",10,palette.muted,false);version.setGravity(Gravity.CENTER);add(version,10);
    }
    private String voiceDescription(){return getSharedPreferences("settings",MODE_PRIVATE).getString("speech_engine","local").equals("system")?SpeechServices.description(this):"本机离线语音 · 模型已随包提供 · 录音不上网";}
    private RadioGroup choices(String[] names,String[] codes,String key,String fallback,boolean refresh){RadioGroup group=new RadioGroup(this);group.setOrientation(RadioGroup.HORIZONTAL);String selected=getSharedPreferences("settings",MODE_PRIVATE).getString(key,fallback);for(int i=0;i<codes.length;i++){RadioButton option=new RadioButton(this);option.setId(View.generateViewId());option.setText(names[i]);option.setTag(codes[i]);option.setButtonDrawable((android.graphics.drawable.Drawable)null);option.setGravity(Gravity.CENTER);option.setTextSize(13);option.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));option.setPadding(0,0,0,0);boolean active=codes[i].equals(selected);option.setTextColor(active?palette.accent:palette.muted);option.setBackground(palette.shape(this,active?palette.soft:palette.surface,active?palette.line:0,11));LinearLayout.LayoutParams params=new RadioGroup.LayoutParams(0,-1,1);params.setMargins(dp(2),0,dp(2),0);group.addView(option,params);if(active)group.check(option.getId());}group.setOnCheckedChangeListener((view,id)->{RadioButton option=view.findViewById(id);if(option==null)return;getSharedPreferences("settings",MODE_PRIVATE).edit().putString(key,(String)option.getTag()).apply();if(refresh){showHome();return;}for(int i=0;i<group.getChildCount();i++){RadioButton item=(RadioButton)group.getChildAt(i);boolean active=item.isChecked();item.setTextColor(active?palette.accent:palette.muted);item.setBackground(palette.shape(this,active?palette.soft:palette.surface,active?palette.line:0,11));}});return group;}
    private LinearLayout card(int padding){LinearLayout view=column();view.setPadding(dp(padding),dp(padding),dp(padding),dp(padding));view.setBackground(palette.shape(this,palette.surface,palette.line,20));return view;}
    private LinearLayout column(){LinearLayout view=new LinearLayout(this);view.setOrientation(LinearLayout.VERTICAL);return view;}
    private LinearLayout row(){LinearLayout view=new LinearLayout(this);view.setOrientation(LinearLayout.HORIZONTAL);return view;}
    private TextView label(String text,int size,int color,boolean medium){TextView view=new TextView(this);view.setText(text);view.setTextSize(size);view.setTextColor(color);view.setTypeface(Typeface.create(medium?"sans-serif-medium":"sans-serif",Typeface.NORMAL));return view;}
    private Button button(String text,boolean primary,View.OnClickListener listener){Button view=new Button(this);view.setText(text);view.setTextSize(14);palette.style(view,primary?palette.accent:palette.soft,primary?palette.onAccent:palette.accent,13,false);view.setOnClickListener(listener);return view;}
    private void add(View view,int top){LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(-1,-2);params.topMargin=dp(top);content.addView(view,params);}
    private int dp(float value){return WordtrailStyle.dp(this,value);}
    private void showNotices(){try(java.io.InputStream stream=getAssets().open("NOTICE.txt")){java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();byte[] chunk=new byte[8192];int count;while((count=stream.read(chunk))!=-1)bytes.write(chunk,0,count);TextView body=label(new String(bytes.toByteArray(),java.nio.charset.StandardCharsets.UTF_8),12,palette.ink,false);body.setTextIsSelectable(true);body.setPadding(dp(18),dp(18),dp(18),dp(18));ScrollView details=new ScrollView(this);details.setBackgroundColor(palette.surface);details.addView(body);new android.app.AlertDialog.Builder(this).setTitle("开源许可").setView(details).setPositiveButton("关闭",null).show();}catch(java.io.IOException error){Toast.makeText(this,"暂时无法读取许可文件",Toast.LENGTH_SHORT).show();}}
}
